# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MccCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc_name', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('dev_token', models.CharField(max_length=200)),
                ('client_customer_id', models.CharField(max_length=200)),
                ('user_agent', models.CharField(max_length=200)),
            ],
        ),
    ]
