# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_id', models.CharField(max_length=200)),
                ('mcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.MccCredential')),
            ],
        ),
    ]
