# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_auto_20171030_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negative',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.CountryCode'),
        ),
    ]
